version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - AWS_ACC=$(echo $CODEBUILD_BUILD_ARN | cut -d':' -f5)
      - REPOSITORY_URI=$AWS_ACC.dkr.ecr.$AWS_REGION.amazonaws.com
      - uname -a
      - java -version
  build:
    commands:
      - echo Build started on `date`
      - mvn package
      - docker build . -t $REPOSITORY_URI/${REPO}:latest
      - echo Build completed on `date`
  post_build:
    commands:
      - $(aws ecr get-login --region $AWS_REGION --no-include-email)
      - aws ecr describe-repositories --registry-id ${AWS_ACC} --repository-name ${REPO}
      - docker push $REPOSITORY_URI/${REPO}:latest
artifacts:
  files:
    - target/spring-petclinic-2.2.0.BUILD-SNAPSHOT.jar