version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo Nothing to do in prebuil
  build:
    commands:
      - echo Build started on `date`
      - mvn install
      - mvn package
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/spring-petclinic-2.2.0.BUILD-SNAPSHOT.jar