# Use the official OpenJDK 8 as a base image
FROM openjdk:8-jdk-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy the JAR file generated by Maven into the container
COPY target/*.jar app.jar

# Expose port 8080 for the application
EXPOSE 8080

# Command to run the application when the container starts
CMD ["java", "-jar", "app.jar"]