#release configuration
#Thu Aug 13 11:15:17 CEST 2026
completedPhase=scm-commit-release
exec.pomFileName=pom.xml
exec.snapshotReleasePluginAllowed=false
pinExternals=false
preparationGoals=clean verify
project.dev.org.springframework.samples\:spring-petclinic=5.0.3-SNAPSHOT
project.rel.org.springframework.samples\:spring-petclinic=5.0.2
project.scm.org.springframework.samples\:spring-petclinic.connection=scm\:git\:https\://github.com/anamaljkovic/spring-petclinic.git
project.scm.org.springframework.samples\:spring-petclinic.developerConnection=scm\:git\:https\://github.com/anamaljkovic/spring-petclinic.git
project.scm.org.springframework.samples\:spring-petclinic.tag=v5.0.0
project.scm.org.springframework.samples\:spring-petclinic.url=https\://github.com/anamaljkovic/spring-petclinic
projectVersionPolicyConfig=<projectVersionPolicyConfig>${projectVersionPolicyConfig}</projectVersionPolicyConfig>\n
projectVersionPolicyId=default
pushChanges=true
releaseStrategyId=default
remoteTagging=true
scm.branchCommitComment=@{prefix} prepare branch @{releaseLabel}
scm.commentPrefix=[maven-release-plugin] 
scm.developmentCommitComment=@{prefix} prepare for next development iteration
scm.releaseCommitComment=@{prefix} prepare release @{releaseLabel}
scm.rollbackCommitComment=@{prefix} rollback the release of @{releaseLabel}
scm.tag=v5.0.2
scm.tagNameFormat=@{project.artifactId}-@{project.version}
scm.url=scm\:git\:https\://github.com/anamaljkovic/spring-petclinic.git
