---
- name: spc deployment
  hosts: localhost
  become: yes
  tasks:
    - name: install java
      ansible.builtin.apt:
        name: openjdk-17-jdk
        state: present
        update_cache: true
    - name: edit the service file
      ansible.builtin.copy:
        dest: /etc/systemd/system/spc.service
        content: |
         [Unit]
         Description=Manage Java service

         [Service]
         WorkingDirectory=/home/ubuntu/spc/target
         ExecStart=java -jar spring-petclinic-3.0.0-SNAPSHOT.jar
         Type=simple
         Restart=on-failure
         RestartSec=10
         [Install]
         WantedBy=multi-user.target
        mode: '777'
    - name: reload the systemd state
      ansible.builtin.systemd:
        name: spc.service
        daemon_reload: true
        enabled: true
        state: "restarted"
