package org.springframework.samples.petclinic.owner;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder

/**
 * Simple business object representing pet temperament.
 *
 * @author Shreyas Prayag
 */
public class PetTemperament {

	/**
	 * The unique identifier for the temperament. This field is mapped to the "id" column
	 * in the "pet_temperament" table. It is automatically generated by the database when
	 * a new temperament is created.
	 */
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer id;

	/**
	 * The Temperament of pet. This field is mapped to the "temperament" column in the
	 * "pet_temperament" table. It cannot be null and should not be empty.
	 */
	@NotNull
	private String temperament;

	public PetTemperament(String temperament) {
		this.temperament = temperament;
	}

}
