ALTER TABLE owners ADD COLUMN IF NOT EXISTS active BOOLEAN DEFAULT TRUE;

ALTER TABLE pets ADD COLUMN IF NOT EXISTS active BOOLEAN DEFAULT TRUE;

CREATE TABLE IF NOT EXISTS vaccine (
    id BIGSERIAL PRIMARY KEY,
    vaccine_name VARCHAR(100) NOT NULL,
    pet_type_id BIGINT NOT NULL,
    CONSTRAINT fk_vaccine_pet_type
        FOREIGN KEY (pet_type_id) REFERENCES types(id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS vaccinations (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vaccination_date DATE NOT NULL,
    description TEXT,
    injected BOOLEAN DEFAULT FALSE,
    pet_id BIGINT NOT NULL,
    vaccine_id BIGINT NOT NULL,
    CONSTRAINT fk_pet
        FOREIGN KEY (pet_id)
        REFERENCES pets(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_vaccinations_vaccine
        FOREIGN KEY (vaccine_id)
        REFERENCES vaccine(id)
        ON DELETE CASCADE
);
