pipeline {
   agent any

   stages {
      stage('Build') {
         steps {
            // Get some code from a GitHub repository
            git 'https://github.com/spring-projects/spring-petclinic.git'

            // Run Maven on a Unix agent.
            sh "./mvnw package"
         }
      }
   }
}
