pipeline {
    agent any

    stages {

        stage('deploy') {
            environment {
               sha = sh(script: 'git rev-parse --short HEAD', returnStdout: true).trim()
            }

            steps {
               withCredentials([azureServicePrincipal(credentialsId: 'jenkins-sp',
                                               subscriptionIdVariable: 'AZURE_SUBSCRIPTION_ID',
                                               clientIdVariable: 'AZURE_CLIENT_ID',
                                               clientSecretVariable: 'AZURE_SECRET',
                                               tenantIdVariable: 'AZURE_TENANT')]) {
                 ansiblePlaybook installation: 'ansible',
                 playbook: 'infra/ansible/staging/main.yaml'
               }
            }
        }
    }
}
