pipeline:
  name: Bhv-pipeline3
  identifier: Bhvpipeline3
  projectIdentifier: SFTY_Training
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: bhavanagithub
        repoName: springpetclinic-work
        build: <+input>
        sparseCheckout: []
  stages:
    - stage:
        name: CI
        identifier: ci
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: false
            override: false
            paths: []
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec:
              size: flex
              imageSpec:
                imageName: ubuntu-24
          execution:
            steps:
              - step:
                  type: Run
                  name: Run Tests
                  identifier: Run_Tests
                  spec:
                    shell: Sh
                    command: |-
                      pwd
                      ls -la
                      whoami
                      docker --version
                      git --version
              - step:
                  type: Run
                  name: Run Basic Checks
                  identifier: Run_Basic_Checks
                  spec:
                    shell: Sh
                    command: |-
                      echo "Running Basic Checks"
                      test -f Dockerfile
                      test -f README.md
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: bhvdocker
                    repo: bhavanab2312/springpetclinic-work
                    tags:
                      - <+pipeline.sequenceId>
          buildIntelligence:
            enabled: false
    - stage:
        name: CD
        identifier: CD
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: ServicekubernetesBhv
            failureStrategies:
              - onFailure:
                  errors:
                    - AllErrors
                  action:
                    type: MarkAsFailure
          environment:
            environmentRef: EnvBhv
            deployToAll: false
            infrastructureDefinitions:
              - identifier: InfraBhv
            failureStrategies:
              - onFailure:
                  errors:
                    - AllErrors
                  action:
                    type: MarkAsFailure
          execution:
            steps:
              - step:
                  type: K8sRollingDeploy
                  name: K8sRollingDeploy_1
                  identifier: K8sRollingDeploy_1
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
                  timeout: 10m
            rollbackSteps: []
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: MarkAsFailure
