name: CI SonarQube

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-test-sonarqube:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Build and Test
        run: ./mvnw clean verify

      - name: SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          ./mvnw sonar:sonar \
            -Dsonar.token=$SONAR_TOKEN \
            -Dsonar.host.url=$SONAR_HOST_URL \
            -Dsonar.qualitygate.wait=true
